### PR TITLE
clean up repetitions & files duplicates

### PR DESCRIPTION
**Pull request by b3bb0**
There were a bit of repetitions all over... I cleanup a bit, just easier to work on and debug... I also sent you an email, let me know what you think

cheers

### CODE REVIEW

**Comment by magdesign** [comment]
Thanks for this great fix.
But I can not merge since it would break the OSC compatibility:
https://github.com/magdesign/PocketVJ-CP-v3/blob/master/sync/osc_control.js

**Comment by b3bb0** [comment]
support for node, sorry I missed it before

**Comment by b3bb0** [comment]
fixed! sorry... I forgot the node part

**Comment by magdesign** [comment]
Thanks for this!
Sorry that it takes so long to test and merge your commit, I saw that you changed index.html to index.php and I need to figured out how integrate this all into my pipeline.
e.g. update command would now leave the index.html on the server and  index.php would be put aside... all this little things must be taken care of so the users don't break their installation.... :-)

**Comment by b3bb0** [comment]
No worries, I'm also got very busy lately... as soon I'm able to breath a
bit more I'll touch base and see how I can properly help :)

**Pull request closed without merging**
